<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linkLihat</name>
   <tag></tag>
   <elementGuidId>39f942b7-38bc-4b8f-bf61-2a7f6cd4fa02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]//div/span[contains(text(),&quot;Lihat&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]//div/span[contains(text(),&quot;Lihat&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
