<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDaftar</name>
   <tag></tag>
   <elementGuidId>c6776aba-8fb6-425d-b91d-1444913a9e47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]//div/form/button[contains(text(),'DAFTAR')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]//div/form/button[contains(text(),'DAFTAR')]</value>
   </webElementProperties>
</WebElementEntity>
